apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SERVICE_ID: {{ .Values.credentials.SERVICE_ID | b64enc }}
  ACCOUNT_SID: {{ .Values.credentials.ACCOUNT_SID | b64enc }}
  AUTH_TOKEN: {{ .Values.credentials.AUTH_TOKEN | b64enc }}
  
  CLOUNDINARY_NAME: {{ .Values.credentials.CLOUNDINARY_NAME | b64enc }}
  CLOUDINARY_API_KEY: {{ .Values.credentials.CLOUDINARY_API_KEY | b64enc }}
  CLOUDINARY_API_SECRET: {{ .Values.credentials.CLOUDINARY_API_SECRET | b64enc }}
  MONGODB_URL: {{ .Values.credentials.MONGODB_URL | b64enc }}
  MONGODB_NAME: {{ .Values.credentials.MONGODB_NAME | b64enc }}
  
  AWS_BUCKET_NAME: {{ .Values.credentials.AWS_BUCKET_NAME | b64enc }}
  AWS_BUCKET_REGION: {{ .Values.credentials.AWS_BUCKET_REGION | b64enc }}
  AWS_ACCESS_KEY: {{ .Values.credentials.AWS_ACCESS_KEY | b64enc }}
  AWS_SECRET_KEY: {{ .Values.credentials.AWS_SECRET_KEY | b64enc }}
  
  RZP_KEY_ID: {{ .Values.credentials.RZP_KEY_ID | b64enc }}
  RZP_KEY_SECRET: {{ .Values.credentials.RZP_KEY_SECRET | b64enc }}

