hosts: django-hello.com

geteway:
  name: django-hello
  servers:
    portNumber: 80
    name: http
    protocol: HTTP
    
virtualService:
  name: django-hello-vs

services:
  version_1: 
    name: version1.default.svc.cluster.local
    weight: 100
  version_2:
    name: version2.default.svc.cluster.local
    weight: 0