{{- if .Values.ingress.enabled  }}
{{- $releaseName := .Release.Name }}
{{- $svcPort := .Values.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host.host }}
    http:
      paths:
        {{- range $host.paths  }}
        - pathType: {{ .pathType }}
          path: {{ .path }}
          backend:
            service:
              name: {{ $releaseName }}-service
              port:
                number: {{ $svcPort }}
        {{- end }}
  {{- end }}            
{{- end }}