apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MONGODB_URL: {{ .Values.credentials.MONGODB_URL | b64enc }}
  MONGODB_NAME: {{ .Values.credentials.MONGODB_NAME | b64enc }}
  RZP_KEY_ID: {{ .Values.credentials.RZP_KEY_ID | b64enc }}
  RZP_KEY_SECRET: {{ .Values.credentials.RZP_KEY_SECRET | b64enc }}
  STRIPE_SECRET_KEY: {{ .Values.credentials.STRIPE_SECRET_KEY | b64enc }}
  CLOUNDINARY_NAME: {{ .Values.credentials.CLOUNDINARY_NAME | b64enc }}
  CLOUDINARY_API_KEY: {{ .Values.credentials.CLOUDINARY_API_KEY | b64enc }}
  CLOUDINARY_API_SECRET: {{ .Values.credentials.CLOUDINARY_API_SECRET | b64enc }}
  HR_MODEL_PASSWORD: {{ .Values.credentials.HR_MODEL_PASSWORD | b64enc }}
  EMAIL_USERNAME: {{ .Values.credentials.EMAIL_USERNAME | b64enc }}
  EMAIL_PASSWORD: {{ .Values.credentials.EMAIL_PASSWORD | b64enc }}
  FROM_EMAIL: {{ .Values.credentials.FROM_EMAIL | b64enc }}
  HOSTURL: {{ .Values.credentials.HOSTURL | b64enc }}
  PAYPAL_CLIENT: {{ .Values.credentials.PAYPAL_CLIENT | b64enc }}
  PAYPAL_SECRET: {{ .Values.credentials.PAYPAL_SECRET | b64enc }}
  PAYPAL_API: {{ .Values.credentials.PAYPAL_API | b64enc }}    