# Default values for jobsway-admin-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: amjedsaleel/jobsway-company-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  port: "4000"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 4000

ingress:
  enabled: true
  hosts:
    - host: jobsway-company.local
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: 500m
  limits:
    cpu: 600m

credentials:
  MONGODB_URL: ""
  MONGODB_NAME: ""
  RZP_KEY_ID: ""
  RZP_KEY_SECRET: ""
  STRIPE_SECRET_KEY: ""
  CLOUNDINARY_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
  JWT_SECRET: ""
  HR_MODEL_PASSWORD: ""
  EMAIL_USERNAME: ""
  EMAIL_PASSWORD: ""
  FROM_EMAIL: ""
  HOSTURL: ""
  PAYPAL_CLIENT: ""
  PAYPAL_SECRET: ""
  PAYPAL_API: ""


startupProbe:
  path: "/"
  initialDelaySeconds: 10
  failureThreshold: 2
  periodSeconds: 5

livenessProbe:
  path: /
  initialDelaySeconds: 1
  failureThreshold: 2
  periodSeconds: 20
