# Default values for jobsway-admin-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: amjedsaleel/jobsway-admin-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  port: "4001"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: 500m
  limits:
    cpu: 600m

credentials:
  monodburl: ""
  databasename: ""

startupProbe:
  path: "/"
  initialDelaySeconds: 10
  failureThreshold: 2
  periodSeconds: 5

livenessProbe:
  path: /
  initialDelaySeconds: 1
  failureThreshold: 2
  periodSeconds: 20
